
import __ASTRO_IMAGE_IMPORT_ZgnQcb from "./assets/pinhole-old.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_Z2rzBgi from "./assets/pinhole-old-2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_Z1rFi3k from "./assets/problem-1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_2sgiCT from "./assets/problem-2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_1i0Kvc from "./assets/problem-3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_7Kdnu from "./assets/problem-4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_1MeIcs from "./assets/panoramic-1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_BYb4K from "./assets/panoramic-2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_Zxgm2W from "./assets/panoramic-3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_Z1HvTaE from "./assets/panoramic-4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md";
import __ASTRO_IMAGE_IMPORT_ZVjKCg from "./assets/lab.png?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fhomelab%2Fhomelab%2Fhomelab.md";
import __ASTRO_IMAGE_IMPORT_2jz7aK from "./assets/network.png?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fhomelab%2Fhomelab%2Fhomelab.md";
export default new Map([["./assets/pinhole-old.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_ZgnQcb], ["./assets/pinhole-old-2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_Z2rzBgi], ["./assets/problem-1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_Z1rFi3k], ["./assets/problem-2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_2sgiCT], ["./assets/problem-3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_1i0Kvc], ["./assets/problem-4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_7Kdnu], ["./assets/panoramic-1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_1MeIcs], ["./assets/panoramic-2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_BYb4K], ["./assets/panoramic-3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_Zxgm2W], ["./assets/panoramic-4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fphotography%2Fpinhole%2Fpinhole-redesign.md", __ASTRO_IMAGE_IMPORT_Z1HvTaE], ["./assets/lab.png?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fhomelab%2Fhomelab%2Fhomelab.md", __ASTRO_IMAGE_IMPORT_ZVjKCg], ["./assets/network.png?astroContentImageFlag=&importer=src%2Fcontent%2Farticle%2Fhomelab%2Fhomelab%2Fhomelab.md", __ASTRO_IMAGE_IMPORT_2jz7aK]]);
		